@startuml c4-theme-default
!include https://unpkg.com/plantuml-style-c4@latest/colors.puml
' uncomment the following line and comment the first to use locally
'!include ./colors.puml

' Colors
' ##################################
!define ELEMENT_FONT_COLOR MD_WHITE

' Person
!define PERSON_BG_COLOR MD_BLUE_800
!define PERSON_BORDER_COLOR MD_BLUE_900
!define EXTERNAL_PERSON_BG_COLOR MD_GRAY_700
!define EXTERNAL_PERSON_BORDER_COLOR MD_GRAY_800

' System
!define SYSTEM_BG_COLOR MD_BLUE_700
!define SYSTEM_BORDER_COLOR MD_BLUE_800
!define EXTERNAL_SYSTEM_BG_COLOR MD_GRAY_600
!define EXTERNAL_SYSTEM_BORDER_COLOR MD_GRAY_700

' Database
!define DATABASE_BG_COLOR MD_BLUE_700
!define DATABASE_BORDER_COLOR MD_BLUE_800

' Actor
!define ACTOR_BG_COLOR MD_BLUE_800
!define ACTOR_BORDER_COLOR MD_BLUE_900
!define INTERNAL_ACTOR_BG_COLOR MD_GRAY_700
!define INTERNAL_ACTOR_BORDER_COLOR MD_GRAY_800

' Container
!define CONTAINER_BG_COLOR MD_BLUE_600
!define CONTAINER_BORDER_COLOR MD_BLUE_600

' Component
!define COMPONENT_BG_COLOR MD_BLUE_200
!define COMPONENT_BORDER_COLOR MD_BLUE_300
!define COMPONENT_FONT_COLOR Black
@enduml
