@startuml core
'!includeurl https://raw.githubusercontent.com/xuanye/plantuml-style-c4/master/colors.puml
' uncomment the following line and comment the first to use locally
!include colors.puml

'!includeurl https://raw.githubusercontent.com/xuanye/plantuml-style-c4/master/skinparam.puml
' uncomment the following line and comment the first to use locally
!include skinparam.puml

!define TECHN_FONT_SIZE 12

!define LAYOUT_TOP_DOWN top to bottom direction
!define LAYOUT_LEFT_RIGHT left to right direction


!procedure LAYOUT_AS_SKETCH()
skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam defaultFontName "Comic Sans MS"
center footer <font color=red>Warning:</font> Created for discussion, needs to be validated
!endprocedure


!define RED_ARROW skinparam ArrowColor Red
!define MEGENTA_ARROW skinparam ArrowColor Magenta
!define GREEN_ARROW skinparam ArrowColor MD_GREEN_200
!define GREY_ARROW skinparam ArrowColor DC_1
!define YELLOW_ARROW skinparam ArrowColor Yellow


' help layer
!define Lay_D(e_from, e_to) e_from -[hidden]D- e_to
!define Lay_U(e_from, e_to) e_from -[hidden]U- e_to
!define Lay_R(e_from, e_to) e_from -[hidden]R- e_to
!define Lay_L(e_from, e_to) e_from -[hidden]L- e_to


!define UserCasePackage(e_alias, e_label) rectangle "==e_label" <<usercase>> as e_alias
!define UserCasePackage(e_alias, e_label, e_type) rectangle "==e_label\n<size:TECHN_FONT_SIZE>[e_type]</size>" <<usercase>> as e_alias

@enduml