''
'' Xuanye theme 
''
'' Author: Xuanye Wong
'' Copyright (c) 2023 by  Xuanye Wong


!$THEME = "4class"

'!$BGCOLOR = "#f5f5f5"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif




!$DC_1= '#BBBBBB'
!$DC_2= '#535353'
!$DC_4= '#2B2B2B'
!$DC_3= '#3C3F41'
!$DC_5= '#438AA3'
!$DC_6= '#5E8A4F'
!$DC_7= '#589DF6'
!$DC_8= '#FF6464'

!$RED_80 = '#750e13'
!$RED_70 = '#a2191f'
!$RED_60 = '#da1e28'
!$RED_50 = '#fa4d56'
!$RED_40 = '#ff8389'
!$RED_30 = '#ffb3b8'
!$RED_20 = '#ffd7d9'
!$RED_10 = '#fff1f1'

!$CYAN_10 = '#e5f6ff'
!$CYAN_20 = '#bae6ff'
!$CYAN_30 = '#82cfff'
!$CYAN_40 = '#33b1ff'
!$CYAN_50 = '#1192e8'
!$CYAN_60 = '#0072c3'
!$CYAN_70 = '#00539a'
!$CYAN_80 = '#003a6d'

!$YELLOW_5= '#FFFDE7'
!$YELLOW_10= '#FFF9C4'
!$YELLOW_20= '#FFF59D'
!$YELLOW_30= '#FFF176'
!$YELLOW_40= '#FFEE58'
!$YELLOW_50= '#FFEB3B'
!$YELLOW_60= '#FDD835'
!$YELLOW_70= '#FBC02D'
!$YELLOW_80= '#F9A825'
!$YELLOW_90= '#F57F17'
!$YELLOW_A100= '#FFFF8D'
!$YELLOW_A200= '#FFFF00'
!$YELLOW_A400= '#FFEA00'
!$YELLOW_A700= '#FFD600'

!$ORANGE_5= '#FFF3E0'
!$ORANGE_10= '#FFE0B2'
!$ORANGE_20= '#FFCC80'
!$ORANGE_30= '#FFB74D'
!$ORANGE_40= '#FFA726'
!$ORANGE_50= '#FF9800'
!$ORANGE_60= '#FB8C00'
!$ORANGE_70= '#F57C00'
!$ORANGE_80= '#EF6C00'
!$ORANGE_90= '#E65100'
!$ORANGE_A100= '#FFD180'
!$ORANGE_A200= '#FFAB40'
!$ORANGE_A400= '#FF9100'
!$ORANGE_A700= '#FF6D00'

!$GREEN_5= '#E8F5E9'
!$GREEN_10= '#C8E6C9'
!$GREEN_20= '#A5D6A7'
!$GREEN_30= '#81C784'
!$GREEN_40= '#66BB6A'
!$GREEN_50= '#4CAF50'
!$GREEN_60= '#43A047'
!$GREEN_70= '#388E3C'
!$GREEN_80= '#2E7D32'
!$GREEN_90= '#1B5E20'
!$GREEN_A100= '#B9F6CA'
!$GREEN_A200= '#69F0AE'
!$GREEN_A400= '#00E676'
!$GREEN_A700= '#00C853'


!$PURPLE_80 ='#491d8b'
!$PURPLE_70 = '#6929c4'
!$PURPLE_60 = '#8a3ffc'
!$PURPLE_50 = '#a56eff'
!$PURPLE_40 = '#be95ff'
!$PURPLE_30 = '#d4bbff'
!$PURPLE_20 = '#e8daff'
!$PURPLE_10 = '#f6f2ff'

!$TEAL_10 = '#d9fbfb'
!$TEAL_20 = '#9ef0f0'
!$TEAL_30 = '#3ddbd9'
!$TEAL_40 = '#08bdba'
!$TEAL_50 = '#009d9a'
!$TEAL_60 = '#007d79'
!$TEAL_70 = '#005d5d'
!$TEAL_80 = '#004144'

!$GRAY_10 = '#f4f4f4'
!$GRAY_20 = '#e0e0e0'
!$GRAY_30 = '#c6c6c6'
!$GRAY_40 = '#a8a8a8'
!$GRAY_50 = '#8d8d8d'
!$GRAY_60 = '#6f6f6f'
!$GRAY_70 = '#525252'
!$GRAY_80 = '#393939'
!$GRAY_90 = '#262626'
!$GRAY_100 = '#161616'

!$BLACK = '#000000'
!$WHITE = '#FFFFFF'


skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false


!$PRIMARY_TEXT = $BLACK
!$PRIMARY_BG_LIGHT = $WHITE
!$PRIMARY_BG = $GRAY_10
!$PRIMARY_BORDER_LIGHT = $GRAY_20
!$PRIMARY_BORDER = $GRAY_80



!$SUCCESS = $GREEN_50
!$WARNING = $ORANGE_80
!$DANGER  = $RED_50

!$ARROW_COLOR = $GRAY_50
!$START_COLOR = $GREEN_50
!$END_COLOR   = $RED_50


!$BORDER_THICKNESS = 1


!procedure $success($msg)
  <font color=$SUCCESS><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$DANGER><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$WARNING><b>$msg
!endprocedure

!procedure $primary_scheme()
	FontColor $PRIMARY_TEXT
	BorderColor $PRIMARY_BORDER
	BackgroundColor $PRIMARY_BG_LIGHT
	RoundCorner 0
!endprocedure


!procedure GRAY_ARROW()
 	skinparam ArrowColor  $GRAY_50
!endprocedure
!procedure BLUE_ARROW()
 	skinparam ArrowColor  $CYAN_50
!endprocedure

!procedure RED_ARROW()
 	skinparam ArrowColor  $RED_50
!endprocedure

!procedure GREEN_ARROW()
 	skinparam ArrowColor  $GREEN_20
!endprocedure
''
'' Global Default Values
''
skinparam defaultFontName       "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"
skinparam defaultFontSize        12
'skinparam dpi                    125
skinparam shadowing              false
skinparam roundcorner            5
skinparam ParticipantPadding     10
skinparam BoxPadding             10
skinparam Padding                4
skinparam ArrowColor             $ARROW_COLOR



!startsub interface

skinparam interface {
	$primary_scheme()	
}
!endsub

!startsub class

skinparam class {

	$primary_scheme()	

	HeaderBackgroundColor $PRIMARY_BG_LIGHT
	StereotypeFontColor $PRIMARY_TEXT
	StereotypeFontSize 9

	BorderThickness $BORDER_THICKNESS


	AttributeFontColor $PRIMARY_TEXT
	AttributeFontSize 10	
	'AttributeIconSize 8
}
!endsub


